baseURL: https://lauragehring.netlify.app/
languageCode: en-us
title: Laura
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A WEBSITE TO GET TO KNOW ME AND MY PROJECTS.
    title: Hi, my name is Laura
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: 14G Avenue Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lgehring.mam2023@london.edu
    enable: yes
    phone:
      - phone: (+41) 79 6776329
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Laura
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com/kostisc
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/laura.gehring.12
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/laura.isag
      - icon: fa-github
        label: GitHub
        url: https://github.com/lauragehr
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/laura-gehring-735b49145/
  image: ''
  name: Laura G
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: is a G
    title: Laura
  tiles:
    enable: yes
    showcase:
      - image: swisslife.jpg
        subtitle: A short biography & CV
        title: Who is Laura G
        url: blogs/cv
      - image: lbs.jpg
        subtitle: The beggining of my journey with R
        title: My pre-class assigment
        url: blogs/pre_course
      - image: code.jpg
        subtitle: My favorite assingment so far
        title: Assignment nb3
        url: blogs/risk_return
#      - image: pic04.jpg
#        subtitle: Nisl Sed Aliquam
#        title: Ipsum
#        url: blogs/ipsum
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "My full name is Laura Shireen Meta Gehring Firouz and I grew up in Switzerland to \r\n
      an Italian mother and an Iranian father. I am lucky enough to speak 3 languages fluently \r\n
      (French, Italian, English) and I am quite proficient in Spanish. Growing up in Lausanne was amazing \r\n
      as we got to enjoy the lake and its activites in summer and then in winter we could go skiing every \r\n
      weekend. After finishing highschool I was accepted at Bocconi University where I studied Economics and \r\n
      management for 3 years. After that I took a gap year where I traveled in South America for three months \r\n
      and got some work experience. Luckily during this time I applied to LBS and got accepted, and here I am now
      \r\n writing my website."
    title: A lil' somethin somehtin about me
    url: blogs